//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class registro_calificacionesEntities : DbContext
    {
        public registro_calificacionesEntities()
            : base("name=registro_calificacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<materia> materia { get; set; }
        public virtual DbSet<notas> notas { get; set; }
        public virtual DbSet<tipousuario> tipousuario { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
